#ifndef TAURUS_MODULE_SLAVE_H
#define TAURUS_MODULE_SLAVE_H

// This definition file is shared between PC and taurus.
#define TAURUS_SLAVE_ID                   0x50

#define TAURUS_SLAVE_COMMAND_ADDR         0x00
#define TAURUS_SLAVE_COMMAND_STATUS_ADDR  0x02
#define TAURUS_SLAVE_INTERRUPT_EVENT_ADDR 0x04
#define TAURUS_SLAVE_ARGUMENT_ADDR        0x06

typedef enum
{
	GET_MODULE_VERSION = 0x01	,
	SET_CUSTOMER_VERSION	,
	GET_CUSTOMER_VERSION	,
	SET_GPIO_POLARITY	,
	GET_GPIO_POLARITY	,
	SET_RADIO_MODE	,//
	GET_RADIO_MODE	,//
	SET_VOLUME	,
	GET_VOLUME	,
	SET_MUTE	,
	GET_MUTE	,
	STORE_PRESET	,
	LOAD_PRESET ,
	STORE_FLASH_DATA	,
	LOAD_FLASH_DATA ,
	CLEAR_FLASH_DATA	,
	GET_DATE	,
	GET_TIME	,
	GET_SIGNAL_STRENGTH ,
	GET_CURRENT_STATE,
	RADIO_COMMAND_MIN = GET_MODULE_VERSION,
	RADIO_COMMAND_MAX = GET_CURRENT_STATE,
	TUNE_DAB_ESEMBLE_FREQUENCY_INDEX = 0x40	,
	GET_DAB_ENSEMBLE_FREQUENCY_INDEX	,
	GET_DAB_ENSEMBLE_NAME	,
	GET_DAB_SERVICE_NAME	,
	GET_DAB_PROGRAM_TYPE	,
	GET_DAB_COMPONENT_TYPE	,
	GET_DAB_BIT_RATE	,
	GET_DAB_AUDIO_MODE	,
	CHOOSE_NEXT_SERVICE_COMPONENT	,
	CHOOSE_PREVIOUS_SERVICE_COMPONENT	,
	CHOOSE_PRESET_SERVICE	,
	CHOOSE_TUNED_SERVICE_COMPONENT ,
	TUNE_CHOSEN_SERVICE_COMPONENT ,
	TUNE_NEXT_SERVICE_COMPONENT_IN_ENSEMBLE	,
	TUNE_PREVIOUS_SERVICE_COMPONENT_IN_ENSEMBLE	,
	GET_DAB_SERVICE_COMPONENT_INFORMATION	,
	TUNE_DAB_SERVICE_COMPONENT	,
	GET_NUMBER_OF_SERVICES	,
	GET_SERVICE_IS_PRIMARY	,
	GET_SERVICE_IS_AVAILABLE	,
	GET_DLS ,
	START_DAB_AUTO_SCAN,
  GET_DAB_PRESET_SERVICE,
  DAB_COMMAND_MIN = TUNE_DAB_ESEMBLE_FREQUENCY_INDEX,
	DAB_COMMAND_MAX = GET_DAB_PRESET_SERVICE,
	GET_FM_FREQUENCY = 0x80	,
	GET_FM_PRESET_FREQUENCY ,
	SET_FM_FREQUENCY	,
	SET_FM_SEEK_START_FREQUENCY ,
	SET_FM_SEEK_STOP_FREQUENCY	,
	START_FM_SEEK	,
	STOP_FM_SEEK	,
	GET_FM_AUDIO_MODE	,
	SET_FM_AUDIO_MODE	,
	GET_FM_PROGRAM_TYPE ,
  GET_FM_STATION_NAME ,
	GET_FM_RADIOTEXT	,
	GET_FM_DEEMPHASIS	,
	SET_FM_DEEMPHASIS	,
	GET_FM_SENSITIVITY	,
	SET_FM_SENSITIVITY	,
	FM_COMMAND_MIN = GET_FM_FREQUENCY,
	FM_COMMAND_MAX = SET_FM_SENSITIVITY,
	CLEAR_COMMAND,
	SLAVE_MODE_MAX
};

typedef enum
{
  PROCESSING_COMMAND = 1	,
  COMMAND_SUCCESS	,
  INVALID_COMMAND	,  
  ILLEGAL_ARGUMENT	,
  SERVICE_UNAVAILABLE	,
  SEEKING_SERVICE	,
  NO_SERVICE_IN_SCAN_LIST,
  EMPTY_PRESET	,  
  CLOCK_UNAVAILABLE	,
  FRAME_SYN_FAIL	,
  FIC_DEC_FAIL	,
  STRING_UNAVAILABLE,
  CLEAR_ERROR_CODE,
  ERROR_CODE_MAX
};

typedef enum
{
  SIGNAL_LOST	= 1,
  SIGNAL_RECOVERY,
  CLEAR_EVENT_CODE,
  EVENT_CODE_MAX
};


#endif
