
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE "mpeg4ip"
#define VERSION "1.2"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#ifdef __cplusplus
extern "C" void std::exit (int) throw (); using std::exit;
#endif
#define WORDS_BIGENDIAN 1
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define SIZEOF_LONG 4
#define SIZEOF_BOOL 1
#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_GETOPT_H 1
#define HAVE_BYTESWAP_H 1
#define HAVE_LINUX_CDROM_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_STRERROR 1
#define HAVE_STRCASESTR 1
#define HAVE_POLL 1
#define HAVE_GETOPT 1
#define HAVE_GETOPT_LONG 1
#define HAVE_GETOPT_LONG_ONLY 1
#define HAVE_GETRUSAGE 1
#define HAVE_SOCKETPAIR 1
#define HAVE_STRSEP 1
#define HAVE_INET_NTOA 1
#define HAVE_IN_PORT_T 1
#define HAVE_SOCKLEN_T 1
#define HAVE_FPOS_T___POS 1
#define HAVE_GTK_2_0 1
#define HAVE_GTK 1
#define HAVE_GLIB_H 1
